### ISSUE TITLE
Change Duration time format: 00:04:32.593 -> 00:04:32

### ISSUE THREAD

**Issue by YauheniPo** [qa-guru/allure-notifications#218]

**Comment by valfirst** [comment]
@YauheniPo would you mind explaining reasons behind this request?

**Comment by YauheniPo** [comment]
not everyone needs such clear time criteria and it would be convenient to set the time yourself in different formats for different regions

**Comment by YauheniPo** [comment]
I can do it

indicate in what place it is more convenient to do this before sending.
