### ISSUE TITLE
Ошибка при использовании Error: Invalid or corrupt jarfile allure-notifications.jar

### ISSUE THREAD

**Issue by ObiWanKaplan** [qa-guru/allure-notifications#268]
Привет!

В первую очередь, спасибо за очень удобную библиотеку)

Сам jar файл подтягивается автоматически в джобу внутри Gitlab на моменте выполнения команды отправки нотификаций. Скачивается через curl: curl -s -X GET -L -o allure-notifications.jar  --header "PRIVATE-TOKEN: <>" "https://gitlab.com/api/v4/projects/36732733/repository/files/allure%2Dnotifications%2D3%2E1%2E1%2Ejar/raw?ref=master"

Перестало работать несколько дне назад с ошибкой:
`Error: Invalid or corrupt jarfile allure-notifications.jar`

Из-за чего возможно такое поведение? Были ли какие-то обновления за последнюю неделю?

**Comment by valfirst** [comment]
> Были ли какие-то обновления за последнюю неделю?

nope, no releases

> Из-за чего возможно такое поведение?

invalid/corrupted file, make sure file is downloaded properly
