### ISSUE TITLE
Incorrect percentage rounding in the telegram notifications

### ISSUE THREAD

**Issue by nicedfx** [qa-guru/allure-notifications#30]
![image](https://user-images.githubusercontent.com/29193061/111880134-9ca65180-89ba-11eb-81de-486efb51916e.png)

Expected:
% of failed tests + ... + % of passed tests should be equal to 100%.
Actual:
% of failed tests + ... + % of passed tests is equal to 99.

**Comment by kadehar** [comment]
Fixed
Will be released soon
