### ISSUE TITLE
Report link is corrupted by the added 'allure' word

### ISSUE THREAD

**Issue by kormachevt** [qa-guru/allure-notifications#61]
I have a problem with this feature. Maybe I use it incorrectly so please feel free to correct me.

https://github.com/qa-guru/allure-notifications/blob/82fa37e9ffeb6c54aaa9bcd680c800b659056b19/src/main/java/guru/qa/allure/notifications/config/helpers/Build.java#L32

Problem: I provide link to the allure server report as such
`https://allure.somecompany.com/allure-api/allure-docker-service/projects/test/reports/1/index.html`
 
 Referenced code adds "allure" at the end.
`https://allure.somecompany.com/allure-api/allure-docker-service/projects/test/reports/1/index.htmlallure`
 
 So the link of report is unusable. 
 Any workarounds ?

**Comment by svasenkov** [comment]
yes, will fix soon

**Comment by svasenkov** [comment]
fixed in 3.1.2
keep empty this config 
![image](https://user-images.githubusercontent.com/9194170/132514433-921b4d8e-7fb8-4342-8ee9-cb7f7ea2e565.png)
